---
# tasks file for boss-ansible-role-bash_it

# TODO: have bash_it run before this shell script
- name: clone bash_it
  git: repo="{{boss__bash_it_repository}}"
      dest="{{bossjones__bash_it_user_home_dir_prefix}}/{{bossjones__user}}/.bash_it"
      update=no
      depth=1
  become: "{{bossjones__user}}"
  become_user: "{{bossjones__user}}"

- name: Register home directory for {{ bossjones__user }}
  shell: >
    getent passwd {{ bossjones__user }} | cut -d: -f6
  changed_when: false
  register: linux_user_home

- name: Register current login shell for {{ bossjones__user }}
  shell: >
    getent passwd {{ bossjones__user }} | cut -d: -f7
  changed_when: false
  register: linux_user_shell

- name: Set facts
  set_fact:
    boss__bash_it_user_home: "{{ linux_user_home.stdout }}"
    boss__bash_it_user_shell: "{{ linux_user_shell.stdout }}"

- name: assert home directory is detected
  assert: { that: boss__bash_it_user_home != "" }

- name: assert current shell is detected
  assert: { that: boss__bash_it_user_shell != "" }

- name: "clone bash_it for {{ bossjones__user }}"
  git:
    repo: "{{ boss__bash_it_repository }}"
    dest: "{{ boss__bash_it_user_home }}/.bash_it"
    version: "{{ boss__bash_it_version }}"
  become: "{{ bossjones__user }}"

- name: "change shell to bash for {{ bossjones__user }}"
  command: "chsh -s /bin/bash {{ bossjones__user }}"
  become_user: root
  when: boss__bash_it_user_shell != "/bin/bash"

- name: "initialize bash_it directories for {{ bossjones__user }}"
  file:
    path: "{{ boss__bash_it_user_home }}/.bash_it/{{ item }}/enabled"
    state: directory
    owner: "{{ bossjones__user }}"
  with_items:
    - "plugins"
    - "aliases"
    - "completion"

- name: "install bash_it plugins for {{ bossjones__user }}"
  file:
    src: "{{ boss__bash_it_user_home }}/.bash_it/plugins/available/{{ item }}.plugin.bash"
    dest: "{{ boss__bash_it_user_home }}/.bash_it/plugins/enabled/{{ item }}.plugin.bash"
    state: link
    owner: "{{ bossjones__user }}"
  with_items: '{{ boss__bash_it_plugins }}'

- name: "install bash_it aliases for {{ bossjones__user }}"
  file:
    src: "{{ boss__bash_it_user_home }}/.bash_it/aliases/available/{{ item }}.aliases.bash"
    dest: "{{ boss__bash_it_user_home }}/.bash_it/aliases/enabled/{{ item }}.aliases.bash"
    state: link
    owner: "{{ bossjones__user }}"
  with_items: '{{ boss__bash_it_aliases }}'

- name: "install bash_it completions for {{ bossjones__user }}"
  file:
    src: "{{ boss__bash_it_user_home }}/.bash_it/completion/available/{{ item }}.completion.bash"
    dest: "{{ boss__bash_it_user_home }}/.bash_it/completion/enabled/{{ item }}.completion.bash"
    state: link
    owner: "{{ bossjones__user }}"
  with_items: '{{ boss__bash_it_completions }}'
