---
- name: Converge
  hosts: all
  become: yes
  become_method: sudo
  environment:
    SHELL: /bin/bash
  roles:
    - role: boss-ansible-role-users
      boss__users_users:
      - username: vagrant
        groups: ['sudo', 'adm', 'vagrant']
        append: yes
        uid: 1000
        gid: 1000
        home: /home/vagrant

    - role: boss-ansible-role-bash_it
